### ISSUE TITLE
Menu & MenuItem missing from archive

### ISSUE THREAD

**Issue by mahmoudzamel** [DominoKit/domino-mvp#28]
the compiler complains not finding import org.dominokit.domino.ui.menu.Menu; and import org.dominokit.domino.ui.menu.MenuItem;
Are they removed? If not how to resolve, if ye what are the replacements?

**Comment by rjeeb** [comment]
It was replaced by Tree, check it out here https://dominokit.github.io/domino-ui-demo/index.html?theme=indigo#tree, kindly note that you can fin the repository for domino-ui under this url https://github.com/DominoKit/domino-ui because this repository is for domino-mvp.

**Comment by mahmoudzamel** [comment]
Yah, it took me a while to figure out which section to go to; but it is pretty cute.
Thank you guys. Keep it up.
