### ISSUE TITLE
Rest request must support 200 (OK) and 204 (No Content) both at a time.

### ISSUE THREAD

**Issue by surajgautam** [DominoKit/domino-mvp#42]
For example, I have a rest request which fetches the content from the backend server. The HTTP status code might be 200 Ok with a list of data and 204 no-content. In the current version, the response is deserialized to the defined model in the case of 200 Ok but if the status code is 204, it throws an error as it cannot deserialize the no-content response.

**Comment by vegegoku** [comment]
if you are making a request to fetch some data then when the data is found you return the data in the response with status code 200 OK, if the data is not found then you return status 404 NOT FOUND.

the OK status will be handled by the success method and the 404 status will be handled in the fail method.

in case you are just checking if the data exists, then the response is void by default and the return status if the data is found is 204 without a body, and 404 if the data is not found. and it handles the same way as the first case.
